5.2.1 연결리스트 정리
bc-back-end-study/book-CS pull request #7
Opened 2022-10-07 15:31 UTC by 0seony

22.10.09 스터디 분량 update - 영선

2022-10-07 15:46 UTC, pjtae0328 reviewed
배열 보다 연결리스트의 삽입/삭제가 빠르다는 말과 연결리스트의 삽입/삭제의 시간복잡도가 O(1)인 것은 순수하게 삽입 혹은 삭제 로직이 수행되는 시간입니다. 사전에 삽입 혹은 삭제할 노드의 위치를 특정하는 것은 탐색에 해당합니다. 연결리스트의 탐색은 익히 아시다 싶이 시간복잡도가 O(n)이 되기 때문에 내가 삭제할 노드를 알고 있거나 삽입할 위치를 아는 상태에서만 O(1)의 빠른 시간복잡도로 삽입/삭제 연산이 가능하다고 이해하시면 됩니다.

2022-10-07 15:53 UTC, pjtae0328 commented
보통 배열이나 연결리스트는 반복문을 통해 전체적으로 데이터를 훑는 경우가 많아서 삭제할노드 혹은 삽입할 위치를 사전에 아는 경우가 많습니다.  그래서 배열보다 삽입/삭제시에 유리하다고 말하는데요 의문 가지신것 처럼 삽입할 위치나 삭제할 노드를 매번 찾아서 수행해야 한다면 배열을 쓰는편이 유리한 경우도 많습니다. 연결리스트는 큰 데이터를 다루는 경우가 아니라면 배열기반의 벡터(arraylist)나 배열을 쓰는게 성능상 좋은 경우가 대부분 입니다.

2022-10-07 15:59 UTC, pjtae0328 commented
조금만 더 tmi 하자면 큐는 삽입, 삭제할 위치가 항상 맨 앞이기에 연결리스트를 쓰면 O(1)으로 삽입 삭제할 위치를 찾을 수 있고 삽입/ 삭제 시에도 O(1)의 시간복잡도를 가지기 때문에 연결리스트로 많이 구현하구요 배열은 맨앞에 데이터를 추가하려면 모든 데이터를 한칸씩 뒤로 미뤄야 하고 삭제하려면 모든 데이터를 당겨야 함으로 삽입 삭제시 항상  O(n)의 시간 복잡도가 필요하기에 원형큐가 아니라면 배열로 큐를 구현하지 않습니다. 이처럼 연결리스트의 삽입 삭제가 배열보다 빠르기 때문에 이 장점을 극대화 가능한 경우에도 연결리스트를 사용합니다.

2022-10-08 06:50 UTC, pjtae0328 approved these changes

2022-10-09 02:24 UTC, lsj8367 requested changes
코멘트 확인 부탁드립니다.

2022-10-09 02:24 UTC, lsj8367 commented on 5장_자료구조/5.2.1 연결 리스트.md
> +```
이부분 블럭 제거해도 좋을것 같아요

2022-10-09 02:25 UTC, lsj8367 approved these changes

2022-10-09 02:27 UTC, prk4224 approved these changes

2022-10-09 02:35 UTC, merged